from . import CamsTransfer
from . import DeepPhotoStyleTransfer
from . import Eb3dColorTransfer
from . import FuzzyColorTransfer
from . import GlobalColorTransfer
from . import GmmEmColorTransfer
from . import HistogramAnalogy
from . import NeuralStyleTransfer
from . import PdfColorTransfer
from . import PSNetStyleTransfer
from . import TpsColorTransfer
from . import MongeKLColorTransfer
from . import FrequencyColorTransfer
from . import HistoGAN
from . import SemanticColorTransfer
from . import FuzzyColorCategoryTransfer
